[Interface]
Address = fc00:2006:0104::2/64
PrivateKey = CB+rN9h9yNEe4brE/qFljuTmW1x0Dpxx4r7TfDz300A=
DNS = 2001:4806:4806::8888

[Peer]
PublicKey = 959zcGL8GcZtWo3teUkmr2ajRvJWX9XQWkGgFN8OqDQ=
AllowedIPs = ::/0
Endpoint = [240d:c000:f06f:9000:52ca:7fac:fac4:0]:51820
PersistentKeepalive = 25