[Interface]
Address = 192.168.8.2/24
PrivateKey = 6FcaEBniliDu1P6QHM7g3z50GDnIy0XgyoaIl9+pum0=
DNS = 8.8.8.8

[Peer]
PublicKey = J3ZWtq5DV/SliRHYO/Z4zov3xTUY6co1VcjVMXrCckw=
Endpoint = 43.108.47.141:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
