[Interface]
Address = fc00:2006:0104::2/64
PrivateKey = wOH2iCjyAYO2P8SHVw4nvn6hPFC+bV1GCd0qMgxWNnQ=
DNS = 2001:4860:4860::8888

[Peer]
PublicKey = ljFg5F6A+nCTl+5AFpuUbJbyGS60HjCv8cyU7hPEBh8=
AllowedIPs = ::/0
Endpoint = [240d:c000:f06f:9000:52ca:7fac:fac4:0]:51820 
PersistentKeepalive = 25
