[Interface]
Address = fc00:2006:0104::1/64
ListenPort = 51820
PrivateKey = SLHVNA/GlKDyHc11kesj7tbRHf4518PItFppgb/wtnM=
PostUp = ip6tables -t nat -A POSTROUTING -s fc00:2006:0104::/64 -o eth0 -j MASQUERADE
PostDown = ip6tables -t nat -D POSTROUTING -s fc00:2006:0104::/64 -o eth0 -j MASQUERADE

[Peer]
PublicKey = kqjnL2jXoLy0riKv98lCrti5+P0Se5oGKrBao+pV+mY=
AllowedIPs = fc00:2006:0104::2/128

[Peer]
PublicKey = rAJjCit9pGgLEVybQEYCPj3QtH9J9xn7sjZB/c0iF28=
AllowedIPs = fc00:2006:0104::3/128