[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
Privatekey = KD+ubynBOK+vLVVd5b1+s4D7Vym8jTwmHq3C9OkTKFM=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[peer]
Publickey = kqjnL2jXoLy0riKv98lCrti5+P0Se5oGKrBao+pV+mY=
AllowedIPs = 10.0.0.2/32

[peer]
Publickey = Rtm3Tn2RBs7OYkALe48H6epPA5dIXqYu1OZN2yWzDwo=
AllowedIPs = 10.0.0.3/32
