[Interface]
Address = 192.168.8.1/24
ListenPort = 51820
PrivateKey = EERgP0C0tLDQVw2Idn1jo010JlJw2cTNWBS/MBvG924=
PostUp = iptables -t nat -A POSTROUTING -s 192.168.8.0/24 -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 192.168.8.0/24 -o eth0 -j MASQUERADE

[Peer]
PublicKey = pnTRnjBgv2/Hyctqt54Uxdqml0DA/H+6oS2CaQWHfmc=
AllowedIPs = 192.168.8.2/32

[Peer]
PublicKey = rAJjCit9pGgLEVybQEYCPj3QtH9J9xn7sjZB/c0iF28=
AllowedIPs = 192.168.8.3/32

[Peer]
PublicKey = q0mwupghT9VOFliVBqBNw1JGMWmUk0LEF73dsLONpy4=
AllowedIPs = 192.168.8.4/32
